### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by PaulMaly** [coderofsalvation/dpd-ratelimit#1]
starting deployd v0.8.9...
{ Error: Cannot find module '/...r/resources/ratelimit/config.json'

Module is just not working. And new Resource type (ratelimit) doesn't appear in dashboard.

**Comment by coderofsalvation** [comment]
Hi!
Thanks for checking out this module.
I think you've missed something in the docs: it mentions the config file.

To make it more clear, I've updated it & published it: 
https://github.com/coderofsalvation/dpd-ratelimit/commit/e54231623b60a797e15b1f5ab039007b2256d5cd
